[package]
name = "shamir_secret_share"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.16"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
